<?php
/**
 * Bordkhan — self-contained installer.
 *
 * Everything (database, site name/url, admin account) is entered right here
 * in the wizard. This file also writes config.php automatically, so you do
 * NOT need to edit any file manually.
 */

error_reporting(E_ALL);
ini_set('display_errors', '1');

if (session_status() === PHP_SESSION_NONE) {
    session_name('bordkhan_installer');
    session_start();
}

$CONFIG = __DIR__ . '/config.php';

/* ---------- helpers ---------- */
function ix(string $k, string $d = ''): string {
    return isset($_POST[$k]) ? trim((string)$_POST[$k]) : $d;
}
function esc(string $v): string {
    return htmlspecialchars($v, ENT_QUOTES, 'UTF-8');
}
function test_pdo(string $host, string $name, string $user, string $pass): array {
    try {
        $dsn = 'mysql:host=' . $host . ';dbname=' . $name . ';charset=utf8mb4';
        $pdo = new PDO($dsn, $user, $pass, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES => false,
        ]);
        return [true, $pdo, ''];
    } catch (Throwable $e) {
        return [false, null, $e->getMessage()];
    }
}
function build_config(string $host, string $name, string $user, string $pass, string $url, string $siteName, string $installKey): string {
    $host = str_replace("'", "\\'", $host);
    $name = str_replace("'", "\\'", $name);
    $user = str_replace("'", "\\'", $user);
    $pass = str_replace("'", "\\'", $pass);
    $url  = str_replace("'", "\\'", rtrim($url, '/'));
    $siteName = str_replace("'", "\\'", $siteName);
    $installKey = str_replace("'", "\\'", $installKey);
    return <<<PHP
<?php
/**
 * Bordkhan configuration — generated by installer.
 */
define('DB_HOST', '$host');
define('DB_NAME', '$name');
define('DB_USER', '$user');
define('DB_PASS', '$pass');
define('SITE_URL', '$url');
define('SITE_NAME', '$siteName');
define('INSTALL_KEY', '$installKey');
define('UPLOAD_DIR', __DIR__ . '/uploads');
define('UPLOAD_URL', SITE_URL . '/uploads');

date_default_timezone_set('Asia/Tehran');
if (session_status() !== PHP_SESSION_ACTIVE) {
    session_name('bordkhan_session');
    session_start();
}

function db(): PDO {
    static \$pdo = null;
    if (\$pdo instanceof PDO) return \$pdo;
    \$dsn = 'mysql:host=' . DB_HOST . ';dbname=' . DB_NAME . ';charset=utf8mb4';
    try {
        \$pdo = new PDO(\$dsn, DB_USER, DB_PASS, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES => false,
        ]);
    } catch (Throwable \$e) {
        http_response_code(500);
        die('<div dir="rtl" style="font-family:Tahoma;padding:40px;max-width:700px;margin:auto"><h2>اتصال به دیتابیس برقرار نشد</h2><p>اطلاعات دیتابیس را از طریق install.php اصلاح کنید.</p></div>');
    }
    return \$pdo;
}
PHP;
}

/* ---------- read existing config to prefill (regex, no execution) ---------- */
$prefill = ['db_host'=>'localhost','db_name'=>'','db_user'=>'','db_pass'=>'','site_url'=>'https://example.com','site_name'=>'بردخان','install_key'=>''];
if (file_exists($CONFIG)) {
    $raw = file_get_contents($CONFIG);
    $map = ['DB_HOST'=>'db_host','DB_NAME'=>'db_name','DB_USER'=>'db_user','DB_PASS'=>'db_pass','SITE_URL'=>'site_url','SITE_NAME'=>'site_name','INSTALL_KEY'=>'install_key'];
    foreach ($map as $const => $key) {
        if (preg_match("/define\s*\(\s*'$const'\s*,\s*(?:getenv\([^)]*\)\s*\?\s*:\s*)?'([^']*)'\s*\)/", $raw, $m)) {
            $prefill[$key] = $m[1];
        }
    }
}

/* ---------- state ---------- */
$step = isset($_POST['step']) ? (int)$_POST['step'] : (isset($_GET['step']) ? (int)$_GET['step'] : 1);
$error = '';
$notice = '';

/* ---------- STEP 1: test database connection ---------- */
if ($_SERVER['REQUEST_METHOD'] === 'POST' && $step === 1) {
    $db = [
        'host' => ix('db_host', $prefill['db_host']) ?: 'localhost',
        'name' => ix('db_name', $prefill['db_name']),
        'user' => ix('db_user', $prefill['db_user']),
        'pass' => ix('db_pass', $prefill['db_pass']),
    ];
    if ($db['name'] === '' || $db['user'] === '') {
        $error = 'نام دیتابیس و نام کاربری را وارد کنید.';
    } else {
        [$ok, $pdo, $msg] = test_pdo($db['host'], $db['name'], $db['user'], $db['pass']);
        if (!$ok) {
            $error = 'اتصال به دیتابیس برقرار نشد: ' . $msg;
        } else {
            $_SESSION['install_db'] = $db;
            $step = 2;
        }
    }
}

/* ---------- STEP 2: install everything ---------- */
if ($_SERVER['REQUEST_METHOD'] === 'POST' && $step === 2) {
    $db = $_SESSION['install_db'] ?? null;
    if (!$db) { $step = 1; $error = 'اطلاعات دیتابیس در دسترس نیست؛ دوباره شروع کنید.'; }
    else {
        $siteName = ix('site_name', $prefill['site_name']) ?: 'بردخان';
        $siteUrl  = rtrim(ix('site_url', $prefill['site_url']), '/');
        $installKey = ix('install_key');
        $adminName  = ix('admin_name') ?: 'مدیر کل';
        $adminPhone = preg_replace('/[^0-9]/', '', ix('admin_phone', '09120000000'));
        $adminEmail = ix('admin_email') ?: null;
        $adminPass  = ix('admin_pass');
        if ($installKey === '') $installKey = bin2hex(random_bytes(16));
        if (!preg_match('/^09[0-9]{9}$/', $adminPhone)) $adminPhone = '09120000000';
        if (strlen($adminPass) < 6) { $step = 2; $error = 'رمز عبور مدیر باید حداقل ۶ کاراکتر باشد.'; }
        elseif ($siteUrl === '' || !preg_match('#^https?://#', $siteUrl)) { $step = 2; $error = 'آدرس سایت باید با http:// یا https:// شروع شود.'; }
        else {
            [$ok, $pdo, $msg] = test_pdo($db['host'], $db['name'], $db['user'], $db['pass']);
            if (!$ok) { $step = 1; $error = 'اتصال به دیتابیس برقرار نشد: ' . $msg; }
            else {
                try {
                    // 1) Write config.php
                    $config = build_config($db['host'], $db['name'], $db['user'], $db['pass'], $siteUrl, $siteName, $installKey);
                    if (@file_put_contents($CONFIG, $config) === false) {
                        throw new RuntimeException('نمی‌توانم فایل config.php را بنویسم. دسترسی پوشه (Permission) را روی 755 یا 777 تنظیم کنید.');
                    }

                    // 2) Schema
                    $sql = file_get_contents(__DIR__ . '/schema.sql');
                    $statements = array_filter(array_map('trim', preg_split('/;\s*(?:\r?\n|$)/', $sql)));
                    foreach ($statements as $st) { if ($st !== '') $pdo->exec($st); }

                    // 3) Upgrade columns (for re-install)
                    $ensureColumn = function (string $table, string $column, string $ddl) use ($pdo): void {
                        try {
                            $q = $pdo->prepare("SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = ? AND column_name = ?");
                            $q->execute([$table, $column]);
                            if ((int)$q->fetchColumn() === 0) $pdo->exec("ALTER TABLE `$table` ADD COLUMN $ddl");
                        } catch (Throwable $e) {}
                    };
                    $ensureColumn('settings', 'meta_description', 'meta_description TEXT NULL');
                    $ensureColumn('settings', 'meta_keywords', 'meta_keywords TEXT NULL');
                    $ensureColumn('settings', 'og_image', 'og_image VARCHAR(500) NULL');
                    $ensureColumn('settings', 'google_analytics', 'google_analytics VARCHAR(100) NULL');
                    $ensureColumn('settings', 'auto_collect_queries', 'auto_collect_queries TEXT NULL');
                    $ensureColumn('settings', 'board_commission_percent', 'board_commission_percent INT NOT NULL DEFAULT 10');
                    $ensureColumn('users', 'seller_status', "seller_status VARCHAR(20) NOT NULL DEFAULT 'none'");
                    $ensureColumn('users', 'referred_rewarded', "referred_rewarded TINYINT(1) NOT NULL DEFAULT 0");
                    $ensureColumn('users', 'seller_note', 'seller_note TEXT NULL');
                    $ensureColumn('users', 'seller_applied_at', 'seller_applied_at DATETIME NULL');
                    $ensureColumn('tips', 'difficulty', "difficulty VARCHAR(20) NOT NULL DEFAULT 'medium'");
                    $ensureColumn('tips', 'source_url', 'source_url VARCHAR(500) NULL');
                    $ensureColumn('tips', 'source_name', 'source_name VARCHAR(200) NULL');

                    // 4) Admin
                    $hash = password_hash($adminPass, PASSWORD_DEFAULT);
                    $pdo->prepare("INSERT INTO users (phone,email,password_hash,name,role,points,balance,referral_code,phone_verified,verified) VALUES (?,?,?,?,'superadmin',5200,0,'ADMIN001',1,1) ON DUPLICATE KEY UPDATE name=VALUES(name), password_hash=VALUES(password_hash), role='superadmin', phone_verified=1, verified=1")
                        ->execute([$adminPhone, $adminEmail, $hash, $adminName]);

                    // 5) Bot account
                    $botHash = password_hash(bin2hex(random_bytes(12)), PASSWORD_DEFAULT);
                    $pdo->prepare("INSERT INTO users (phone,email,password_hash,name,role,points,balance,referral_code,phone_verified,verified,bio) VALUES ('09100000000','bot@bordkhan.local',?,'سامانه جمع‌آوری هوشمند','admin',0,0,'BOT0001',1,1,'گردآوری خودکار قلق‌های تعمیراتی') ON DUPLICATE KEY UPDATE role='admin'")
                        ->execute([$botHash]);

                    // 6) Settings
                    $defaultSources = json_encode([
                        'https://www.reddit.com/r/AskElectronics/.rss',
                        'https://www.reddit.com/r/ElectronicsRepair/.rss',
                        'https://hackaday.com/feed/',
                        'https://blog.adafruit.com/feed/',
                        'https://www.ifixit.com/News/rss',
                    ], JSON_UNESCAPED_UNICODE);
                    $cronKey = bin2hex(random_bytes(8));
                    $defaultQueries = "تعمیر مادربرد\nرفع مشکل روشن نشدن لپ‌تاپ\nتعمیر پاور سوئیچینگ\nعیب‌یابی کارت گرافیک\nتعمیر موبایل شارژ نمی‌شود\nmotherboard repair\nlaptop no power fix\ngraphics card artifact fix\npower supply repair";
                    $pdo->prepare("INSERT INTO settings (id,site_title,hero_title,hero_subtitle,meta_description,auto_collect_sources,auto_collect_queries,auto_collect_cron_key) VALUES (1,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE site_title=VALUES(site_title), meta_description=VALUES(meta_description)")
                        ->execute([$siteName, 'بازار تخصصی قلق‌های تعمیراتی بردهای الکترونیکی', 'راه‌حل‌های واقعی و تست‌شده از تعمیرکاران حرفه‌ای — سریع پیدا کن، مطمئن تعمیر کن، درآمد بساز.', 'بازار تخصصی قلق‌های تعمیراتی بردهای الکترونیکی؛ راه‌حل‌های واقعی و تست‌شده از تعمیرکاران حرفه‌ای.', $defaultSources, $defaultQueries, $cronKey]);

                    // 7) Categories
                    // Full category tree: level-1 parent → level-2 brand → level-3 model
                    $categories = [
                        ['پاور','⚡',[
                            ['گرین',['GP530','GP600','GP750']],
                            ['کورسیر',['VS','CV','RM']],
                            ['ترمالتیک',['Smart','Toughpower']],
                            ['کولر مستر',['MWE','GM']],
                            ['متفرقه',[]],
                        ]],
                        ['مادربرد','🖥️',[
                            ['گیگابایت',['B450','B550','B650','H310','H510']],
                            ['ایسوس',['Prime','TUF Gaming','ROG Strix','ProArt']],
                            ['MSI',['MAG','Bazooka','Tomahawk','Mortar']],
                            ['ASRock',['Steel Legend','Phantom','Pro RS']],
                        ]],
                        ['لپ‌تاپ','💻',[
                            ['ایسوس',['TUF Gaming','ROG','VivoBook','ZenBook']],
                            ['لنوو',['IdeaPad','Legion','ThinkPad','Yoga']],
                            ['اچ‌پی',['Pavilion','Victus','Omen','EliteBook']],
                            ['دل',['Inspiron','XPS','Latitude','G15']],
                            ['ایسر',['Aspire','Nitro','Swift']],
                            ['مک بوک',['Air M1','Air M2','Pro 13','Pro 14','Pro 16']],
                        ]],
                        ['کارت گرافیک','🎮',[
                            ['انویدیا',['GTX 1050/1060/1650','RTX 2060','RTX 3060','RTX 4060','RTX 4070']],
                            ['AMD',['RX 580','RX 6600','RX 6700XT','RX 7600']],
                        ]],
                        ['مانیتور و تلویزیون','📺',[
                            ['سامسونگ',['Odyssey','M5','UA50','Neo QLED']],
                            ['ال‌جی',['UltraGear','QLED','C2/C3']],
                            ['سونی',['Bravia X75','Bravia X80']],
                            ['گنوتی',['M1','M2']],
                        ]],
                        ['موبایل و تبلت','📱',[
                            ['شیائومی',['ردمی نوت 9','ردمی نوت 10','ردمی نوت 11','ردمی نوت 12','پوکو X3','پوکو X4']],
                            ['سامسونگ',['گلکسی A12','گلکسی A32','گلکسی A52','گلکسی A54','گلکسی S21','گلکسی S22','گلکسی S23']],
                            ['آیفون',['11','12','13','14','15']],
                            ['هواوی',['Y6','Y8','P30','Nova']],
                            ['تبلت',['آیپد','سامسونگ Tab','شیائومی Pad']],
                        ]],
                        ['لوازم خانگی','🧺',[
                            ['لباسشویی',['سامسونگ','ال‌جی','بوش','پاکشوما']],
                            ['ظرفشویی',['سامسونگ','ال‌جی','بوش']],
                            ['یخچال و فریزر',['سامسونگ','ال‌جی','اسنوا','دوو']],
                            ['تلویزیون خانگی',['سامسونگ','ال‌جی','سونی']],
                        ]],
                        ['بردهای صنعتی','🏭',[
                            ['اینورتر',['زیمنس','دلتا','شنایدر','ABB']],
                            ['PLC',['زیمنس S7','میتسوبیشی FX','دلتا DVP']],
                            ['درایو و CNC',['فانوک','زیمنس','هایده‌نهایین']],
                        ]],
                        ['آداپتور و شارژر','🔌',[
                            ['لپ‌تاپ',['ایسوس','لنوو','اچ‌پی','دل','۹۰ وات','۱۲۵ وات']],
                            ['موبایل',['شارژر آیفون','شارژر سامسونگ','شارژر شیائومی']],
                            ['صنعتی',['۱۲ ولت','۲۴ ولت','۴۸ ولت']],
                        ]],
                        ['سایر','🔧',[]],
                    ];
                    $find = $pdo->prepare('SELECT id FROM categories WHERE name=? AND parent_id IS NULL LIMIT 1');
                    $ins = $pdo->prepare('INSERT INTO categories (parent_id,name,slug,icon) VALUES (?,?,?,?)');
                    $childFind = $pdo->prepare('SELECT id FROM categories WHERE name=? AND parent_id=? LIMIT 1');
                    foreach ($categories as [$cname, $icon, $children]) {
                        $find->execute([$cname]); $parentRow = $find->fetchColumn();
                        if (!$parentRow) { $ins->execute([null, $cname, 'cat-' . md5($cname), $icon]); $parentRow = $pdo->lastInsertId(); }
                        foreach ($children as $childEntry) {
                            $childName = is_array($childEntry) ? $childEntry[0] : $childEntry;
                            $grandchildren = is_array($childEntry) ? ($childEntry[1] ?? []) : [];
                            $childFind->execute([$childName, $parentRow]);
                            $childId = $childFind->fetchColumn();
                            if (!$childId) { $ins->execute([$parentRow, $childName, 'cat-' . md5($cname . $childName), null]); $childId = $pdo->lastInsertId(); }
                            foreach ($grandchildren as $grand) {
                                $childFind->execute([$grand, $childId]);
                                if (!$childFind->fetchColumn()) $ins->execute([$childId, $grand, 'cat-' . md5($cname . $childName . $grand), null]);
                            }
                        }
                    }

                    // 8) Uploads dir
                    if (!is_dir(__DIR__ . '/uploads')) @mkdir(__DIR__ . '/uploads', 0755, true);

                    $_SESSION['done'] = [
                        'url' => $siteUrl, 'phone' => $adminPhone, 'pass' => $adminPass,
                    ];
                    $step = 3;
                } catch (Throwable $e) {
                    $error = $e->getMessage();
                }
            }
        }
    }
}

$done = $step === 3 && isset($_SESSION['done']);
?>
<!doctype html>
<html lang="fa" dir="rtl">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="robots" content="noindex,nofollow">
<title>نصب بردخان</title>
<style>
*{box-sizing:border-box}body{font-family:Tahoma,Arial,sans-serif;background:linear-gradient(135deg,#073d2e,#075b48);color:#14251f;padding:28px 14px;margin:0;min-height:100vh}
.box{max-width:660px;margin:22px auto;background:#fff;padding:30px;border-radius:20px;box-shadow:0 20px 60px #021c1424}
h1{color:#087f5b;margin:0 0 4px;font-size:23px}.sub{color:#6b776f;font-size:13px;margin:0 0 20px}
.steps{display:flex;gap:8px;margin-bottom:22px}
.steps .s{flex:1;text-align:center;padding:9px;border-radius:10px;font-size:12px;font-weight:bold;background:#edf2f0;color:#61706a}
.steps .s.on{background:#078659;color:#fff}.steps .s.done{background:#e0f6eb;color:#087f5b}
label{display:block;margin:14px 0 6px;font-size:12px;font-weight:bold;color:#42514a}
input,select{width:100%;padding:12px;border:1px solid #ccd9d3;border-radius:10px;font:inherit;font-size:14px;background:#fff}
input:focus,select:focus{outline:0;border-color:#078659;box-shadow:0 0 0 3px #07865918}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}
.hint{font-size:11px;color:#8b9791;margin-top:5px}
button{margin-top:20px;width:100%;background:#078659;color:#fff;border:0;border-radius:11px;padding:14px;font:inherit;font-weight:bold;cursor:pointer;font-size:15px}
button:hover{background:#056d49}
.btn-ghost{margin-top:10px;width:100%;background:#edf2f0;color:#61706a;border:0;border-radius:11px;padding:12px;font:inherit;font-weight:bold;cursor:pointer;font-size:13px}
.ok{background:#e4f7ed;padding:16px;border-radius:12px;line-height:2.1;font-size:14px}
.ok b{color:#087f5b}
.ok .loginbox{background:#fff;border:1px dashed #087f5b;border-radius:10px;padding:12px;margin-top:10px;font-family:monospace;font-size:13px;direction:ltr;text-align:left;line-height:1.9}
.err{background:#fee8e7;color:#a22;padding:13px;border-radius:12px;direction:ltr;text-align:left;font-size:12px;word-break:break-word;margin-bottom:8px}
.notice{background:#fff8e4;color:#6a4a00;padding:12px;border-radius:10px;font-size:11px;line-height:2;margin-top:12px}
.warn{background:#ffe9eb;color:#b42f45;padding:12px;border-radius:10px;font-size:11px;line-height:2;margin-top:12px}
@media(max-width:560px){.grid{grid-template-columns:1fr}.box{padding:20px}}
</style>
</head>
<body>
<div class="box">
  <h1>⚙️ نصب بردخان</h1>
  <p class="sub">نصب کامل و آسان — همه اطلاعات را همین‌جا وارد کنید</p>

  <?php if ($error): ?><div class="err"><?=esc($error)?></div><?php endif; ?>

  <?php if ($done): ?>
    <div class="steps">
      <div class="s done">✓ دیتابیس</div><div class="s done">✓ سایت و مدیر</div><div class="s on">نصب شد</div>
    </div>
    <div class="ok">
      ✅ نصب با موفقیت انجام شد!<br>
      <b>آدرس ورود مدیریت:</b>
      <div class="loginbox"><?=esc($_SESSION['done']['url'] . '/login')?></div>
      <b>شماره موبایل:</b> <span dir="ltr"><?=esc($_SESSION['done']['phone'])?></span><br>
      <b>رمز عبور:</b> <span dir="ltr"><?=esc($_SESSION['done']['pass'])?></span>
    </div>
    <div class="warn">⚠️ همین حالا فایل <b>install.php</b> را حذف یا تغییرنام دهید و سپس رمز مدیر را از پنل تغییر دهید.</div>
    <a href="<?=esc($_SESSION['done']['url'])?>/" style="text-decoration:none"><button type="button">🚀 ورود به سایت</button></a>

  <?php elseif ($step === 2): ?>
    <div class="steps"><div class="s done">✓ دیتابیس</div><div class="s on">سایت و مدیر</div><div class="s">نصب</div></div>
    <form method="post">
      <input type="hidden" name="step" value="2">
      <label>نام سایت</label>
      <input name="site_name" value="<?=esc($prefill['site_name'])?>" placeholder="بردخان">
      <label>آدرس کامل سایت (با https://)</label>
      <input name="site_url" dir="ltr" value="<?=esc($prefill['site_url'])?>" placeholder="https://example.com">
      <div class="grid">
        <div><label>نام مدیر کل</label><input name="admin_name" placeholder="مدیر کل"></div>
        <div><label>ایمیل مدیر (اختیاری)</label><input name="admin_email" dir="ltr" placeholder="admin@example.com"></div>
      </div>
      <div class="grid">
        <div><label>شماره موبایل مدیر (برای ورود)</label><input name="admin_phone" dir="ltr" value="09120000000" placeholder="09120000000"></div>
        <div><label>رمز عبور مدیر (حداقل ۶ کاراکتر)</label><input name="admin_pass" type="password" placeholder="رمز عبور"></div>
      </div>
      <label>کلید نصب (خالی بگذارید تا تصادفی ساخته شود)</label>
      <input name="install_key" dir="ltr" value="<?=esc($prefill['install_key'] === 'CHANGE_THIS_INSTALL_KEY' ? '' : $prefill['install_key'])?>" placeholder="اختیاری">
      <div class="warn">⚠️ اگر قبلاً نصب کرده‌اید و دوباره نصب می‌کنید، همه جدول‌ها و داده‌های قبلی پاک و از نو ساخته می‌شوند.</div>
      <button type="submit">🚀 نصب نهایی</button>
    </form>

  <?php else: ?>
    <div class="steps"><div class="s on">دیتابیس</div><div class="s">سایت و مدیر</div><div class="s">نصب</div></div>
    <form method="post">
      <input type="hidden" name="step" value="1">
      <div class="grid">
        <div><label>میزبان دیتابیس (Host)</label><input name="db_host" dir="ltr" value="<?=esc($prefill['db_host'] === 'localhost' ? 'localhost' : $prefill['db_host'])?>"><div class="hint">معمولاً localhost</div></div>
        <div><label>نام دیتابیس (Database)</label><input name="db_name" dir="ltr" value="<?=esc($prefill['db_name'])?>" placeholder="cpuser_bordkhan"></div>
      </div>
      <div class="grid">
        <div><label>نام کاربری دیتابیس (User)</label><input name="db_user" dir="ltr" value="<?=esc($prefill['db_user'])?>" placeholder="cpuser_bordkhan_user"></div>
        <div><label>رمز دیتابیس (Password)</label><input name="db_pass" dir="ltr" type="password" value="<?=esc($prefill['db_pass'])?>"></div>
      </div>
      <div class="notice">📌 این اطلاعات را از cPanel در بخش <b>MySQL Databases</b> می‌سازید. ابتدا یک دیتابیس و کاربر بسازید، کاربر را با تمام دسترسی‌ها به دیتابیس متصل کنید، سپس همان اطلاعات را اینجا وارد کنید.</div>
      <button type="submit">ادامه و تست اتصال ←</button>
    </form>
  <?php endif; ?>
</div>
</body>
</html>
